### ISSUE TITLE
wrong highlighting

### ISSUE THREAD

**Issue by daimor** [dgileadi/mumps-language-vscode#1]
in this code, some variables highlighted as a commands

```
A  B:C  D E F G=H:I:J K:L M N O,P Q:R  S T=UVW X YZ
E
```

**Comment by dgileadi** [comment]
This is not surprising—it's a result of using regular expressions to detect commands (and other syntax features) instead of parsing the code using an actual interpreter. And, of course, it's exacerbated by M[UMPS] allowing variables to have the same names as commands.

The bottom line is that parsing with an actual interpreter would fix these issues, but I don't plan to implement this—besides making the extension much more complex it would also require installing said interpreter. So for the foreseeable future this extension will get some things wrong, including what you mentioned here.

**Comment by daimor** [comment]
Sorry, that I confused you. You thought that I don't know it. But I said that, some variables highlighted as a commands. In this sample of code,
![image](https://cloud.githubusercontent.com/assets/1212251/20076407/50c9fcd0-a549-11e6-9ae0-14463e5996c8.png)

As you can see here
D E - E here should a label, but highlighted as a command, and even tooltip shows it as command ELSE
K:L M - M variable as well as L, but highlighted as a command, and tooltip shows MERGE.

And I'm still sure that it is a bug, and should be fixed. 
I'm not going to use this extension anyway, because I'm mostly Caché Developer, but not think that it is matter.
